default_platform(:ios)

lane :tests do
  run_tests(scheme: "SwiftyCrypto")
end

desc "Does a static analysis of the project. Configure the options in .swiftlint.yml"
lane :lint do
        swiftlint(
          mode: :lint,
          output_file: "swiftlint.result.json", 
          config_file: ".swiftlint.yml"
        )
end